/* SPDX-FileCopyrightText: 2026 LichtFeld Studio Authors
 *
 * SPDX-License-Identifier: GPL-3.0-or-later */

#include "core/camera.hpp"
#include "core/logger.hpp"
#include "core/parameters.hpp"
#include "core/tensor.hpp"
#include "training/normal_auto_generate.hpp"

#include "core/error.hpp"
#include "core/source_site.hpp"
#include <expected>
#include <filesystem>
#include <fstream>
#include <gtest/gtest.h>
#include <memory>
#include <span>
#include <string>
#include <string_view>
#include <vector>

namespace fs = std::filesystem;

namespace {

    class LogHandlerGuard {
    public:
        explicit LogHandlerGuard(lfs::core::LogHandler handler)
            : token_(lfs::core::Logger::get().add_log_handler(std::move(handler))) {}

        ~LogHandlerGuard() {
            lfs::core::Logger::get().remove_log_handler(token_);
        }

        LogHandlerGuard(const LogHandlerGuard&) = delete;
        LogHandlerGuard& operator=(const LogHandlerGuard&) = delete;

    private:
        lfs::core::LogHandlerToken token_;
    };

    std::shared_ptr<lfs::core::Camera> make_camera(const std::string& name,
                                                   const fs::path& image_path,
                                                   const fs::path& normal_path = {}) {
        auto cam = std::make_shared<lfs::core::Camera>(
            lfs::core::Tensor::eye(3, lfs::core::Device::CPU),
            lfs::core::Tensor::zeros({3}, lfs::core::Device::CPU),
            100.0f, 100.0f, 32.0f, 32.0f,
            lfs::core::Tensor(), lfs::core::Tensor(),
            lfs::core::CameraModelType::PINHOLE,
            name, image_path, fs::path{}, 64, 64, 0);
        if (!normal_path.empty())
            cam->set_normal_path(normal_path);
        return cam;
    }

    void write_file(const fs::path& path, const std::string& contents = "x") {
        fs::create_directories(path.parent_path());
        std::ofstream out(path, std::ios::binary);
        ASSERT_TRUE(out.is_open()) << path;
        out << contents;
    }

} // namespace

TEST(NormalAutoGenerateDecision, NeedsGenerationIffFlagsAndMissingMaps) {
    std::vector<std::shared_ptr<lfs::core::Camera>> cameras;
    cameras.push_back(std::make_shared<lfs::core::Camera>());
    cameras.push_back(std::make_shared<lfs::core::Camera>());

    EXPECT_FALSE(lfs::training::normal_auto_generate_needed(false, true, 0.05f, cameras));
    EXPECT_FALSE(lfs::training::normal_auto_generate_needed(true, false, 0.05f, cameras));
    EXPECT_FALSE(lfs::training::normal_auto_generate_needed(true, true, 0.0f, cameras));
    EXPECT_TRUE(lfs::training::normal_auto_generate_needed(true, true, 0.05f, cameras));

    const auto temp = fs::temp_directory_path() / "lfs_normal_auto_generate_decision";
    fs::remove_all(temp);
    fs::create_directories(temp);
    const auto existing = temp / "have.png";
    write_file(existing);
    cameras[0]->set_normal_path(existing);
    cameras[1]->set_normal_path(existing);
    EXPECT_TRUE(cameras[0]->has_normal());
    EXPECT_FALSE(lfs::training::normal_auto_generate_needed(true, true, 0.05f, cameras));

    cameras[1]->set_normal_path({});
    EXPECT_TRUE(lfs::training::normal_auto_generate_needed(true, true, 0.05f, cameras));

    cameras[1]->set_has_image(false);
    EXPECT_FALSE(lfs::training::normal_auto_generate_needed(true, true, 0.05f, cameras));

    fs::remove_all(temp);
}

TEST(NormalAutoGenerateIntegration, GeneratesOnlyMissingAndAssociatesCameras) {
    const auto root = fs::temp_directory_path() / "lfs_normal_auto_generate_missing";
    fs::remove_all(root);
    const auto images = root / "images";
    const auto normals = root / "normals";
    fs::create_directories(images);

    const auto img_a = images / "a.jpg";
    const auto img_b = images / "b.jpg";
    const auto img_c = images / "c.jpg";
    write_file(img_a);
    write_file(img_b);
    write_file(img_c);
    write_file(normals / "a.png");

    auto cam_a = make_camera("a.jpg", img_a, normals / "a.png");
    auto cam_b = make_camera("b.jpg", img_b);
    auto cam_c = make_camera("c.jpg", img_c);
    ASSERT_TRUE(cam_a->has_normal());
    ASSERT_FALSE(cam_b->has_normal());
    ASSERT_FALSE(cam_c->has_normal());

    std::vector<std::shared_ptr<lfs::core::Camera>> cameras{cam_a, cam_b, cam_c};

    lfs::core::param::TrainingParameters params;
    params.dataset.data_path = root;
    params.dataset.images = "images";
    params.optimization.use_normal_loss = true;
    params.optimization.normal_auto_generate = true;
    params.optimization.normal_loss_weight = 0.05f;

    std::vector<fs::path> requested;
    const auto outcome = lfs::training::ensure_training_normal_maps(
        params, cameras,
        [&](const std::span<const lfs::training::NormalAutoGenerateJob> jobs,
            const lfs::training::NormalGenerateProgress& progress)
            -> std::expected<void, lfs::Error> {
            for (std::size_t i = 0; i < jobs.size(); ++i) {
                requested.push_back(jobs[i].image_path);
                write_file(jobs[i].output_path, "normal");
                if (progress)
                    progress(i + 1, jobs.size(), jobs[i].image_path.filename().string());
            }
            return {};
        });

    ASSERT_FALSE(outcome.failed);
    EXPECT_TRUE(outcome.generated);
    ASSERT_EQ(requested.size(), 2u);
    EXPECT_EQ(requested[0], img_b);
    EXPECT_EQ(requested[1], img_c);
    EXPECT_TRUE(cam_a->has_normal());
    EXPECT_TRUE(cam_b->has_normal());
    EXPECT_TRUE(cam_c->has_normal());
    EXPECT_TRUE(fs::is_regular_file(normals / "b.png"));
    EXPECT_TRUE(fs::is_regular_file(normals / "c.png"));

    requested.clear();
    const auto second = lfs::training::ensure_training_normal_maps(
        params, cameras,
        [&](const std::span<const lfs::training::NormalAutoGenerateJob> jobs,
            const lfs::training::NormalGenerateProgress&)
            -> std::expected<void, lfs::Error> {
            for (const auto& job : jobs)
                requested.push_back(job.image_path);
            return {};
        });
    EXPECT_FALSE(second.generated);
    EXPECT_TRUE(requested.empty());
    EXPECT_EQ(second.existing_count, 3u);

    fs::remove_all(root);
}

TEST(NormalAutoGenerateIntegration, FailingEstimatorLeavesTrainingWithoutPrior) {
    const auto root = fs::temp_directory_path() / "lfs_normal_auto_generate_fail";
    fs::remove_all(root);
    const auto images = root / "images";
    fs::create_directories(images);
    const auto img = images / "only.jpg";
    write_file(img);

    auto cam = make_camera("only.jpg", img);
    std::vector<std::shared_ptr<lfs::core::Camera>> cameras{cam};

    lfs::core::param::TrainingParameters params;
    params.dataset.data_path = root;
    params.dataset.images = "images";
    params.optimization.use_normal_loss = true;
    params.optimization.normal_auto_generate = true;
    params.optimization.normal_loss_weight = 0.05f;

    std::vector<std::string> warnings;
    LogHandlerGuard guard([&](lfs::core::LogLevel level, const lfs::core::SourceSite&,
                              const std::string_view message) {
        if (level >= lfs::core::LogLevel::Warn)
            warnings.emplace_back(message);
    });

    const auto outcome = lfs::training::ensure_training_normal_maps(
        params, cameras,
        [](const std::span<const lfs::training::NormalAutoGenerateJob>,
           const lfs::training::NormalGenerateProgress&)
            -> std::expected<void, lfs::Error> {
            return std::unexpected(lfs::make_error(lfs::ErrorInit{
                .code = lfs::ErrorCode::Internal,
                .domain = lfs::ErrorDomain::Training,
                .user_message = "ONNX Runtime cannot initialise",
                .detection = LFS_SOURCE_SITE_CURRENT(),
            }));
        });

    EXPECT_TRUE(outcome.failed);
    EXPECT_FALSE(outcome.generated);
    EXPECT_FALSE(cam->has_normal());
    ASSERT_FALSE(warnings.empty());
    EXPECT_NE(outcome.warning.find("Continuing without the prior"), std::string::npos);
    bool saw_warning = false;
    for (const auto& line : warnings) {
        if (line.find("Continuing without the prior") != std::string::npos &&
            line.find("ONNX Runtime cannot initialise") != std::string::npos) {
            saw_warning = true;
        }
    }
    EXPECT_TRUE(saw_warning);

    fs::remove_all(root);
}

TEST(NormalAutoGenerateIntegration, PrefersFullResolutionImagesFolder) {
    const auto root = fs::temp_directory_path() / "lfs_normal_auto_generate_fullres";
    fs::remove_all(root);
    const auto original = root / "images";
    const auto training = root / "images_8";
    fs::create_directories(original);
    fs::create_directories(training);

    const auto orig_a = original / "a.jpg";
    const auto train_a = training / "a.jpg";
    write_file(orig_a, "full");
    write_file(train_a, "small");

    auto cam = make_camera("a.jpg", train_a);
    std::vector<std::shared_ptr<lfs::core::Camera>> cameras{cam};

    lfs::core::param::TrainingParameters params;
    params.dataset.data_path = root;
    params.dataset.images = "images_8";
    params.optimization.use_normal_loss = true;
    params.optimization.normal_auto_generate = true;
    params.optimization.normal_loss_weight = 0.05f;

    std::vector<lfs::training::NormalAutoGenerateJob> seen;
    const auto outcome = lfs::training::ensure_training_normal_maps(
        params, cameras,
        [&](const std::span<const lfs::training::NormalAutoGenerateJob> jobs,
            const lfs::training::NormalGenerateProgress&)
            -> std::expected<void, lfs::Error> {
            for (const auto& job : jobs) {
                seen.push_back(job);
                write_file(job.output_path, "normal");
            }
            return {};
        });

    ASSERT_FALSE(outcome.failed);
    EXPECT_TRUE(outcome.generated);
    ASSERT_EQ(seen.size(), 1u);
    EXPECT_EQ(seen[0].image_path, orig_a);
    EXPECT_EQ(seen[0].output_path, root / "normals" / "a.png");
    EXPECT_TRUE(cam->has_normal());

    fs::remove_all(root);
}

TEST(NormalAutoGenerateIntegration, FallsBackToTrainingFolderWhenImagesMissing) {
    const auto root = fs::temp_directory_path() / "lfs_normal_auto_generate_no_fullres";
    fs::remove_all(root);
    const auto training = root / "images_8";
    fs::create_directories(training);
    const auto train_a = training / "a.jpg";
    write_file(train_a);

    auto cam = make_camera("a.jpg", train_a);
    std::vector<std::shared_ptr<lfs::core::Camera>> cameras{cam};

    lfs::core::param::TrainingParameters params;
    params.dataset.data_path = root;
    params.dataset.images = "images_8";
    params.optimization.use_normal_loss = true;
    params.optimization.normal_auto_generate = true;
    params.optimization.normal_loss_weight = 0.05f;

    std::vector<fs::path> requested;
    const auto outcome = lfs::training::ensure_training_normal_maps(
        params, cameras,
        [&](const std::span<const lfs::training::NormalAutoGenerateJob> jobs,
            const lfs::training::NormalGenerateProgress&)
            -> std::expected<void, lfs::Error> {
            for (const auto& job : jobs) {
                requested.push_back(job.image_path);
                write_file(job.output_path, "normal");
            }
            return {};
        });

    ASSERT_FALSE(outcome.failed);
    ASSERT_EQ(requested.size(), 1u);
    EXPECT_EQ(requested[0], train_a);

    fs::remove_all(root);
}

TEST(NormalAutoGenerateIntegration, OverwritesExistingMapWhenCameraHasNone) {
    const auto root = fs::temp_directory_path() / "lfs_normal_auto_generate_overwrite";
    fs::remove_all(root);
    const auto images = root / "images";
    const auto normals = root / "normals";
    fs::create_directories(images);
    const auto img = images / "stale.jpg";
    write_file(img);
    write_file(normals / "stale.png", "stale");

    auto cam = make_camera("stale.jpg", img);
    ASSERT_FALSE(cam->has_normal());
    std::vector<std::shared_ptr<lfs::core::Camera>> cameras{cam};

    lfs::core::param::TrainingParameters params;
    params.dataset.data_path = root;
    params.dataset.images = "images";
    params.optimization.use_normal_loss = true;
    params.optimization.normal_auto_generate = true;
    params.optimization.normal_loss_weight = 0.05f;

    std::vector<fs::path> outputs;
    const auto outcome = lfs::training::ensure_training_normal_maps(
        params, cameras,
        [&](const std::span<const lfs::training::NormalAutoGenerateJob> jobs,
            const lfs::training::NormalGenerateProgress&)
            -> std::expected<void, lfs::Error> {
            for (const auto& job : jobs) {
                outputs.push_back(job.output_path);
                write_file(job.output_path, "fresh");
            }
            return {};
        });

    ASSERT_FALSE(outcome.failed);
    ASSERT_EQ(outputs.size(), 1u);
    EXPECT_EQ(outputs[0], normals / "stale.png");
    EXPECT_TRUE(cam->has_normal());
    std::ifstream in(normals / "stale.png");
    std::string body;
    in >> body;
    EXPECT_EQ(body, "fresh");

    fs::remove_all(root);
}
